# setup for ansible pull
---
- hosts: localhost
  connection: local
  become: true

  pre_tasks: 
    - name: update/upgrade system
      tags: always, apt
      apt:
        upgrade: dist
        update_cache: yes
      changed_when: false

  tasks:
    - include_tasks: tasks/base_sources.yml
    - include_tasks: tasks/base_packages.yml
    - include_tasks: tasks/communication_packages.yml
    - include_tasks: tasks/dev_fpm.yml
    - include_tasks: tasks/dev_blackbox.yml
    - include_tasks: tasks/dev_sources.yml
    - include_tasks: tasks/dev_terraform.yml
    - include_tasks: tasks/dev_cloudclis.yml

  handlers:
    - name: apt_update
      apt:
        update_cache: yes

