- name: Install dev cloud clis via Snap
  community.general.snap:
    name:
      - google-cloud-cli
      - kubectl
    classic: yes

- name: Install dev cloud clis via Snap non-classic
  community.general.snap:
    name:
      kops
