- name: Git checkout blackbox
  ansible.builtin.git:
    repo: https://github.com/StackExchange/blackbox.git
    dest: /srv/checkout/blackbox

- name: Build and package blackbox
  make:
    chdir: /srv/checkout/blackbox
    target: packages-deb

- name: Install blackbox package
  apt:
    deb: /root/debbuild-stack_blackbox/stack-blackbox_1.0-521_all.deb