---

- name: Ensure the 'aur_builder' user exists
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
    uid: '{{ aur_user_uid }}'

- name: Ensure the 'aur_builder' user can run 'sudo pacman' without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'

- name: Ensure the system package definition is up to date
  community.general.pacman:
    update_cache: true
    upgrade: false

- name: Check if yay AUR helper is available
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay_stat_result

- name: Ensure the packages for building AUR packages are installed
  community.general.pacman:
    state: present
    name:
      - fakeroot
      - git
      - gnupg

- name: Clone yay AUR helper repository
  become_user: aur_builder
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    version: master
    dest: /tmp/yay
  when: not yay_stat_result.stat.exists

- name: Install yay AUR helper package
  become_user: aur_builder
  ansible.builtin.command:
    chdir: /tmp/yay
    cmd: makepkg -si --noconfirm
  when: not yay_stat_result.stat.exists

- name: Ensure yay AUR helper package is up to date
  become_user: aur_builder
  kewlfft.aur.aur:
    name:
      - yay
  when: yay_stat_result.stat.exists

- name: Ensure the desired packages are installed
  community.general.pacman:
    state: present
    name:
      - acpid
      - base-devel
      - curl
      - exfat-utils
      - git
      - git-lfs
      - gnupg
      - iw
      - linux-headers
      - lshw
      - man-db
      - man-pages
      - networkmanager
      - ntp
      - openssh
      - realtime-privileges
      - sudo
      - time
      - tree
      - vim
      - wget
      - which
      - whois
      - xclip
      - xterm
      - zsh
